language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t forestfrag3d .
  - mkdir ffdata
  - chown -R $USER:$USER ffdata
  - docker run --rm -v $(pwd)/ffdata:/data -it forestfrag3d /code/run.sh test

notifications:
  email:
    recipients:
      - wenzeslaus@gmail.com
    on_success: change
    on_failure: always
