language: generic

sudo: required

services:
  - docker

install:
  - docker build -t forestfrag3d .
  - mkdir ffdata

script:
  - docker run --rm -v $(pwd)/ffdata:/data -it forestfrag3d /code/run.sh test
